layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.8401673
  lightness: 0
  rhythmicContrast: 1
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.5242537
name: My Way
