collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5247201
color:
  saturation: 0
  brandStrength: 0.8638059
  lightness: 1
  brandColors:
    - '#885D5C'
    - '#CFD0CE'
    - '#303A4B'
    - '#CE9C88'
    - '#77291E'
  rhythmicContrast: 1
layout_spectrum: 1
name: My Way
